package_name: delivery_model
training_data_file: delivery_data.csv
test_data_file: test_data_.csv
pipeline_save_file: delivery_model_pipeline

target: delayed

# set train/test split
test_size: 0.3

# to set the random seed
random_state: 101

categorical_vars:
  - Type
  - Category Name
  - Customer Segment
  - Department Name
  - Market
  - Order Region
  - Order Status
  - Product Category Id
  - Shipping Mode Clean